# api/config/packages/api_platform.yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api/resources' # yaml or xml directory configuration
    formats:
        json: ['application/json']
        jsonld:   ['application/ld+json']
